### ISSUE TITLE
Endpoint for study room availability

### ISSUE THREAD

**Issue by andrew-wang0** [icssc/anteater-api#2]
## Summary

Create endpoints for `study_room` data

- [ ] REST endpoint for `study_room` data
- [ ] GraphQL endpoint for `study_room` data

**Comment by alexanderl19** [comment]
Wooo nice! Also are we not yet returning availability? Tried a couple ids and didn't get the slots field.

**Comment by ecxyzzy** [comment]
> Wooo nice! Also are we not yet returning availability? Tried a couple ids and didn't get the slots field.

Yeah we're not returning availability yet - tracking the follow-up in #46
